// Sprites dos animais, desenhados a partir das referências: coelho, sapo e cervo copiados
// pixel a pixel (o cervo com a cabeça virada para a frente e as pernas refeitas por quadro,
// em animais.js); o esquilo redesenhado em metade do tamanho, com as cores da referência.
// Todos virados para a direita. Cada caractere é 1 pixel e '.' é transparente; `eixo` é a
// coluna do centro do corpo, que fica sobre o `x` do animal (os pés ficam na última linha).

const PALETA_ESQUILO = { o: '#120806', b: '#856155', d: '#b2805b', c: '#e9b58d', e: '#fee0ae' };

const QUADROS_ESQUILO = {
  sentado: [
    { eixo: 9, linhas: [
      '..........o.o..',
      '.oooo....obobo.',
      'obbbbo..obdddo.',
      'obbbbbo.obddodo',
      '.oobbbo.bdeeeeo',
      '...obbo.oeeeoo.',
      '...obboobdeeo..',
      '..obbobddeeco..',
      '..obboddddcco..',
      '..obbbdddddo...',
      '...obbbddcco...',
      '....ooooooooo..',
    ] },
    { eixo: 9, linhas: [
      '...............',
      '..........o.o..',
      '.oooo....obobo.',
      'obbbbo..obdddo.',
      'obbbbbo.obddodo',
      '.oobbbo.bdeeeeo',
      '...obboooeeeoo.',
      '...obbobddeeco.',
      '..obbobddddcco.',
      '..obboddddddo..',
      '..obbbbddddco..',
      '...ooooooooooo.',
    ] },
  ],
  correndo: [
    { eixo: 11, linhas: [
      '..ooo.............',
      '.obbbo............',
      'obbbbbo......o.o..',
      'obboobbo....obobo.',
      'oo...obbooooobddo.',
      '.......obdddddodo.',
      '.......obddddddeeo',
      '......oddddddeeoo.',
      '.....occddcco.o...',
      '....occo...occo...',
      '....oo......oo....',
    ] },
    { eixo: 11, linhas: [
      '..ooo.............',
      '.obbbo............',
      'obbbbbo...........',
      'obboobbo.....o.o..',
      'oo...obbo...obobo.',
      '......obooooobddo.',
      '......obdddddodeo.',
      '......obddddddeeeo',
      '.......oddddddeoo.',
      '........occccco...',
      '.........oo.oo....',
    ] },
  ],
};

const PALETA_COELHO = { o: '#222230', b: '#fafcf9', c: '#c9dbf2', e: '#d6566b' };

// sentado → impulso (esticado para cima, ainda com as patas no chão) → salto (esticado no ar).
const QUADROS_COELHO = {
  sentado: { eixo: 7, linhas: [
    '.......oo.oo..',
    '......obbocco.',
    '......obbocco.',
    '......obbocco.',
    '......obbbbbo.',
    '.oo...obbbbbbo',
    'obboooobbbbbbo',
    'obbbbbbbbebbeo',
    '.ocbbbbbbbbbbo',
    '.obbbbbbcbbbo.',
    '.obbcbbbbcco..',
    '.obbbccbbbbo..',
    '..obbbbcbbbbo.',
  ] },
  impulso: { eixo: 7, linhas: [
    '.......oo.oo..',
    '......obbocco.',
    '......obbocco.',
    '......obbocco.',
    '......obbbbbo.',
    '......obbbbbbo',
    '......obbbbbbo',
    '......obbebbeo',
    '.oo..obbbbbbbo',
    'obboobbbcbbbo.',
    'obbbbbbbbcco..',
    '.ocbbbcbbbbo..',
    '.obbbbbcbbbbo.',
    '.obbbbboooooo.',
    '.obbbco.......',
    '..obbo........',
    '..obo.........',
    '..obo.........',
    '..oo..........',
  ] },
  salto: { eixo: 10, linhas: [
    '..........oo.oo..',
    '.........obbocco.',
    '.........obbocco.',
    '.........obbocco.',
    '.........obbbbbo.',
    '....oo...obbbbbbo',
    '...obboooobbbbbbo',
    '...obbbbbbbbebbeo',
    '....ocbbbbbbbbbbo',
    '....obbbbbbcbbbo.',
    '...obbbcbbbbcco..',
    'ooobbbboobbbbbo..',
    'obbbbbo..oobbbo..',
    '.ooooo.....ocbo..',
    '............ooo..',
  ] },
};

const PALETA_SAPO = { o: '#020304', c: '#95dd3f', d: '#5fc412', e: '#f95352', f: '#fdeb6d', h: '#730631' };

const QUADROS_SAPO = {
  parado: { eixo: 6, linhas: [
    '.....oo.oo...',
    '....occocco..',
    '...odccccco..',
    '..odccoccoco.',
    '.odccecccceco',
    'oddcccffffffo',
    'odddcffffffo.',
    'odccdcffffo..',
    '.occcocoodo..',
  ] },
  pulo: { eixo: 9, linhas: [
    '........oo.oo...',
    '.......occocco..',
    '......odcoccoco.',
    '.....odcecccceco',
    '....odcccffffffo',
    '...odddcffffffo.',
    '...oddddcffffo..',
    '..occdddoocoodo.',
    '..occooo..oo.oo.',
    '.occo...........',
    'occo............',
    'ooo.............',
  ] },
  papo: { eixo: 6, linhas: [
    '....oo........',
    '...occoo......',
    '..oocoecooo...',
    '.occcccffffo..',
    '.occocffffffo.',
    '..ocecfffffffo',
    '..occffffffffo',
    '.odccffffffffo',
    'oddccffffffffo',
    'odddcfffffffo.',
    'odccdcfffffo..',
    '.occcocoodo...',
  ] }, // coaxando
  boca: { eixo: 6, linhas: [
    '......oo....',
    '....ooccoo..',
    '...occcoeco.',
    '...ococchho.',
    '..oocechhho.',
    '.odcccfeehho',
    'oddccffeehfo',
    'odddcfffffo.',
    'odccdcffffo.',
  ] },
  agachado: { eixo: 6, linhas: [
    '.....oo.oo...',
    '..oooccocco..',
    '.oddccoccoco.',
    'odddcecccceco',
    'odccdcffffffo',
  ] },
};

const PALETA_CERVO = {
  a: '#cd633d',
  b: '#ab5233',
  c: '#70422a',
  d: '#5e2c1a',
  e: '#b8896f',
  f: '#e24e0f',
  g: '#8b624c',
  h: '#f49974',
  i: '#432418',
  j: '#f0c185',
  k: '#d2a775',
  l: '#260f07',
};

// Corpo do cervo até a barriga; as pernas são desenhadas por cima em cada quadro.
const CORPO_CERVO = {
  frente: [
    '..............................',
    '......................a.......',
    '..............a.......a.a.....',
    '...............a......bbb.....',
    '...............bb......c......',
    '..............a.c....cdd......',
    '...............ccc.d..dee.....',
    '.................cdd...ef.....',
    '..................dd...gf.....',
    '.................gggg.ccgg....',
    '..................hfggcgggg...',
    '...................hfggggigg..',
    '....................ggggghgggi',
    '....................ggggfhhggg',
    '....................gcggfffgg.',
    '....................ggggdgg...',
    '......................ddcgj...',
    '.....jc...............dcggj...',
    '.....jgcjeejee........ccggj...',
    '.....jjcejeejeje......cgggj...',
    '.......ccggkjeejeje.eecgggj...',
    '......dcggkegggkegjejggggkj...',
    '.....dccggggkgkgeekggggggkj...',
    '.....dcgggggggggkggggggggjj...',
    '.....dcgggggggggggggggggkj....',
    '......cgggggeegggggggggekj....',
    '......cgggeeeckgggkdgggej.....',
    '......cggeeecckjjjkdggegj.....',
    '......cegeecc.....dcggekj.....',
  ],
  // a pose da referência: cabeça virada para trás
  tras: [
    '.................................',
    '........................a........',
    '......................a.a.......a',
    '......................bbb......a.',
    '.......................c......bb.',
    '.......................ddc....c.a',
    '......................eed..d.ccc.',
    '......................fe...ddc...',
    '......................fg...dd....',
    '.....................ggcc.gggg...',
    '....................ggggcggfh....',
    '...................ggiggggfh.....',
    '.................iggghggggg......',
    '.................ggghhfgggg......',
    '..................ggfffggcg......',
    '....................ggggdgg......',
    '......................ddcgj......',
    '.....jc...............dcggj......',
    '.....jgcjeejee........ccggj......',
    '.....jjcejeejeje......cgggj......',
    '.......ccggkjeejeje.eecgggj......',
    '......dcggkegggkegjejggggkj......',
    '.....dccggggkgkgeekggggggkj......',
    '.....dcgggggggggkggggggggjj......',
    '.....dcgggggggggggggggggkj.......',
    '......cgggggeegggggggggekj.......',
    '......cgggeeeckgggkdgggej........',
    '......cggeeecckjjjkdggegj........',
    '......cegeecc.....dcggekj........',
  ],
};

// Pássaro no chão ou num galho, com as cores de CORES_PASSARO (cenario.js) e pés (P).
const QUADROS_AVE_POUSADA = {
  pousado: [
    '......HH..',
    '.....HHEY.',
    '..BBBBBH..',
    '.BWWWWBL..',
    'TWwwWWLL..',
    'T..LLLL...',
    '....P.P...',
  ],
  bicando: [
    '..........',
    '..........',
    '..BBBBB...',
    '.BWWWWBHH.',
    'TWwwWWLHHE',
    'T..LLLL.HY',
    '....P.P...',
  ],
};

// Asa (A), borda da asa (a) e corpo (b).
const QUADROS_BORBOLETA = {
  aberta: [
    'aA.Aa',
    'AAbAA',
    '.AbA.',
  ],
  fechada: [
    '.A.A.',
    '.AbA.',
    '..b..',
  ],
};

const CORES_BORBOLETA = [
  { A: '#f5d547', a: '#c9962a' },
  { A: '#f08a24', a: '#3a2418' },
  { A: '#f4f1e8', a: '#a9a397' },
  { A: '#6cb4ee', a: '#2f5f9a' },
];
